# Interfaccia sulla quale ascoltare per richieste DHCP
interface=eth1

# Range di indirizzi DHCP
dhcp-range=192.168.237.10,192.168.237.20,255.255.255.0,12h

# DNS da fornire ai client
dhcp-option=6,192.168.122.1

# Gateway/router
dhcp-option=3,192.168.237.1

# File dei lease (leggibile)
dhcp-leasefile=/var/lib/misc/dnsmasq.leases

# Logging
log-dhcp
log-queries
