[sssd]
services           = nss, pam
config_file_version = 2
debug_level         = 2
domains             = example

[domain/example]
# AD General
description         = Dominio AD ***ANONYMIZED***
debug_level         = 2
enumerate           = false

# Providers
id_provider         = ldap
auth_provider       = ldap

# LDAP General
ldap_schema         = AD
cache_credentials   = true
case_sensitive      = false
ldap_id_mapping     = true
use_fully_qualified_names = false
override_homedir    = /home/%d/%u
default_shell       = /bin/bash

# LDAP connection parameters
ldap_uri            = ldaps://dc01.example.local,ldaps://dc02.example.local
ldap_search_base    = OU=Users,DC=example,DC=local
ldap_tls_cacert     = /etc/openldap/certs/example.pem
ldap_tls_reqcert    = allow
ldap_default_bind_dn      = svc_ldap@example.local
ldap_default_authtok      = ********            # (redacted)
ldap_default_authtok_type = password
